CREATE TABLE HOTELS (
    ID NUMBER NOT NULL,
    CONSTRAINT HOTEL_ID PRIMARY KEY(ID),
    HOTEL_NAME VARCHAR(30) NOT NULL,
    COUNRTY VARCHAR(30) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    STREET VARCHAR(80) NOT NULL
);

CREATE TABLE USERS (
    ID NUMBER NOT NULL,
    CONSTRAINT USER_ID PRIMARY KEY (ID),
    U_NAME VARCHAR(30) NOT NULL,
    U_PASSWORD VARCHAR(30) NOT NULL,
    COUNRTY VARCHAR(30) NOT NULL,
    U_AGE NUMBER NOT NULL,
    U_TYPE VARCHAR(5) NOT NULL CHECK (U_TYPE IN ('ADMIN', 'USER'))
);

CREATE TABLE ROOMS (
    ID NUMBER NOT NULL,
    CONSTRAINT ROOM_ID PRIMARY KEY(ID),
    GUESTS_NUM NUMBER NOT NULL,
    PRICE NUMBER(*,2),
    BREAKFAST VARCHAR(5) NOT NULL CHECK (BREAKFAST IN ('FALSE', 'TRUE')),
    PETS VARCHAR(5) NOT NULL CHECK (PETS IN ('FALSE', 'TRUE')),
    DATE_FROM DATE,
    HOTEL_ID NUMBER REFERENCES HOTELS(ID)
);

CREATE TABLE ORDERS (
    ID NUMBER NOT NULL,
    U_ID NUMBER NOT NULL REFERENCES USERS(ID),
    R_ID NUMBER NOT NULL REFERENCES ROOMS(ID),
    DATE_FROM DATE NOT NULL,
    DATE_TO DATE NOT NULL,
    MONEY_PAID NUMBER(*,2),
    CONSTRAINT ORDER_ID PRIMARY KEY(ID, U_ID, R_ID)
);

DROP TABLE HOTEL;
DROP TABLE USER_DB;

INSERT INTO USERS VALUES (
12, 'Vasya','qwerty','UA', 21, 'ADMIN'  );

